version: 4.0.{build}
image: Visual Studio 2022
configuration:
- Release
platform:
- x86
- x64
branches:
  only:
    - master
    - devel
  except:
    - gh-pages
install:
- cmd: git submodule -q update --init
- cmd: choco install dotnet-sdk --pre 
- cmd: choco install advanced-installer
- ps: |
    $env:PATH="C:\\Program Files (x86)\\Caphyon\\Advanced Installer 19.4\\bin\\x86\\;%PATH%"
    .\AdvancedInstaller.com /register a154fa587445df371a718f08290b7c2b
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- nuget restore
skip_commits:
  files:
    - doc/*
    - .github/*
    - extras/*
    - '**/*.md'
build_script:
- cmd: dotnet publish "%APPVEYOR_BUILD_FOLDER%\DS4WindowsWPF.sln" -c %CONFIGURATION% -r win-%PLATFORM% --no-self-contained -o "%APPVEYOR_BUILD_FOLDER%\artifacts\%PLATFORM%" -p:WapProjPath="C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\DesktopBridge" 
- ps: "%APPVEYOR_BUILD_FOLDER%\\publishall.ps1"
after_build:
- cmd: 7z a %APPVEYOR_PROJECT_NAME%-%PLATFORM%-v%APPVEYOR_BUILD_VERSION%.zip "%APPVEYOR_BUILD_FOLDER%\artifacts\%PLATFORM%\*"
- cmd: 7z a %APPVEYOR_PROJECT_NAME%-%PLATFORM%.zip "%APPVEYOR_BUILD_FOLDER%\artifacts\%PLATFORM%\*"
- cmd: "C:\\Program Files (x86)\\Caphyon\\Advanced Installer 19.4\\bin\\x86\\AdvancedInstaller.com /build %APPVEYOR_BUILD_FOLDER%\\Installer\\Ds4Windows.Installer.aip"
test: off
cache:
- '%USERPROFILE%\.nuget\packages'
artifacts:
  - path: $(APPVEYOR_PROJECT_NAME)-*.zip
    name: $(APPVEYOR_PROJECT_NAME)
deploy:
- provider: Environment
  name: BUILDBOT
  on:
    appveyor_repo_tag: true