version: 4.0.{build}
image: Visual Studio 2022
configuration:
- Release
platform:
- Any CPU
branches:
  only:
    - master
    - devel
  except:
    - gh-pages
install:
- cmd: git submodule -q update --init
- cmd: choco install advanced-installer
- ps: |
    $env:publishPath = $env:APPVEYOR_BUILD_FOLDER + "/publishAll.ps1"
    $env:adiInstallPath = "C:/Program Files (x86)/Caphyon/Advanced Installer 19.4/bin/x86/AdvancedInstaller.com"
    & "$env:adiInstallPath" /register a154fa587445df371a718f08290b7c2b
- ps: if ( $(Test-Path -Path .\vpatch.exe) -ne $True) { Invoke-WebRequest "https://github.com/nefarius/vpatch/releases/latest/download/vpatch.exe" -OutFile vpatch.exe }
- cmd: .\vpatch.exe --stamp-version "%APPVEYOR_BUILD_VERSION%" --target-file ".\CommonProjectProperties.targets" --csproj.assembly-version --csproj.file-version --csproj.version
before_build:
- nuget restore
skip_commits:
  files:
    - doc/*
    - .github/*
    - extras/*
    - '**/*.md'
build_script:
- ps: |
    & $env:publishPath
after_build:
- ps: |
    $installerOutputPath = $env:APPVEYOR_BUILD_FOLDER + "/artifacts"
    $installerProjectDir = $env:APPVEYOR_BUILD_FOLDER + "/Installer"
    $installerProjectPath = $installerProjectDir + "/Ds4Windows.Installer.aip"
    & "$env:adiInstallPath" /build $installerProjectPath 

    $opath = $installerOutputPath + "/DS4Windows.Setup.exe"
    $inpath = $installerProjectDir + "/Setup Files/DS4Windows.exe"

    Write-Output "About to try and move"
    New-Item $installerOutputPath -itemtype directory
    Move-Item -Path $inpath -Destination $opath -Force
test: off
cache:
- '%USERPROFILE%\.nuget\packages'
- .\vpatch.exe
artifacts:
  - path: "artifacts\\DS4Windows.Setup.exe"
    name: $(APPVEYOR_PROJECT_NAME)
deploy:
- provider: Environment
  name: BUILDBOT
  on:
    appveyor_repo_tag: true