version: 4.0.{build}
image: Visual Studio 2022
configuration:
- Release
platform:
- x86
- x64
branches:
  only:
    - master
    - devel
  except:
    - gh-pages
install:
- cmd: git submodule -q update --init
- cmd: choco install advanced-installer
- ps: |
    $env:publishPath = %APPVEYOR_BUILD_FOLDER%/publishAll.ps1
    $env:adiInstallPath = "C:/Program Files (x86)/Caphyon/Advanced Installer 19.4/bin/x86/AdvancedInstaller.com"
    Start-Process -FilePath $env:adiInstallPath.ToString() -ArgumentList "/register a154fa587445df371a718f08290b7c2b"
- cmd: choco install dotnet-sdk --pre 
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- nuget restore
skip_commits:
  files:
    - doc/*
    - .github/*
    - extras/*
    - '**/*.md'
build_script:
- ps: |
    & $env:publishPath
after_build:
- cmd: 7z a %APPVEYOR_PROJECT_NAME%-%PLATFORM%-v%APPVEYOR_BUILD_VERSION%.zip "%APPVEYOR_BUILD_FOLDER%\artifacts\%PLATFORM%\*"
- cmd: 7z a %APPVEYOR_PROJECT_NAME%-%PLATFORM%.zip "%APPVEYOR_BUILD_FOLDER%\artifacts\%PLATFORM%\*"
- ps: |
    $installerOutputPath = "%APPVEYOR_BUILD_FOLDER%/artifacts/"
    $installerProjectDir = "%APPVEYOR_BUILD_FOLDER%/Installer"
    $installerProjectPath = "/build %installerProjectDir%Ds4Windows.Installer.aip"
    Start-Process -FilePath $env:adiInstallPath.ToString() -ArgumentList $installerProjectPath
    Move-Item -Path "%installerProjectDir%/Setup Files/DS4Windows.exe" -Destination "%installerOutputPath%/DS4Windows.Setupp.exe"
test: off
cache:
- '%USERPROFILE%\.nuget\packages'
artifacts:
  - path: $(APPVEYOR_PROJECT_NAME)-*.zip
    name: $(APPVEYOR_PROJECT_NAME)
deploy:
- provider: Environment
  name: BUILDBOT
  on:
    appveyor_repo_tag: true