version: 4.0.{build}
image: Visual Studio 2022
configuration:
- Release
platform:
- x86
- x64
branches:
  only:
    - master
    - devel
  except:
    - gh-pages
install:
- cmd: git submodule -q update --init
- cmd: vs_Community.exe modify --installPath "C:\Program Files\Microsoft Visual Studio\2022\Community" --add Microsoft.VisualStudio.ComponentGroup.WindowsAppSDK.Cs --quiet --wait
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- nuget restore
skip_commits:
  files:
    - doc/*
    - .github/*
    - extras/*
    - '**/*.md'
build_script:
- cmd: dotnet publish "%APPVEYOR_BUILD_FOLDER%\DS4WindowsWPF.sln" -c %CONFIGURATION% -r win-%PLATFORM% --no-self-contained -o "%APPVEYOR_BUILD_FOLDER%\artifacts\%PLATFORM%"
after_build:
- cmd: 7z a %APPVEYOR_PROJECT_NAME%-%PLATFORM%-v%APPVEYOR_BUILD_VERSION%.zip "%APPVEYOR_BUILD_FOLDER%\artifacts\%PLATFORM%\*"
- cmd: 7z a %APPVEYOR_PROJECT_NAME%-%PLATFORM%.zip "%APPVEYOR_BUILD_FOLDER%\artifacts\%PLATFORM%\*"
test: off
cache:
- '%USERPROFILE%\.nuget\packages'
artifacts:
  - path: $(APPVEYOR_PROJECT_NAME)-*.zip
    name: $(APPVEYOR_PROJECT_NAME)
deploy:
- provider: Environment
  name: BUILDBOT
  on:
    appveyor_repo_tag: true