version: 4.0.{build}
image: Visual Studio 2019
configuration:
- Release
platform:
- x86
- x64
branches:
  only:
    - master
    - devel
  except:
    - gh-pages
install:
- cmd: git submodule -q update --init
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- nuget restore
skip_commits:
  files:
    - doc/*
    - .github/*
    - extras/*
    - '**/*.md'
build:
  project: $(APPVEYOR_BUILD_FOLDER)\DS4WindowsWPF.sln
after_build:
- cmd: dotnet publish "%APPVEYOR_BUILD_FOLDER%\DS4WindowsWPF.sln" -c %CONFIGURATION% -r win-%PLATFORM% --no-build -o "%APPVEYOR_BUILD_FOLDER%\artifacts\%PLATFORM%"
- cmd: 7z a %APPVEYOR_PROJECT_NAME%-%PLATFORM%-v%APPVEYOR_BUILD_VERSION%.zip "%APPVEYOR_BUILD_FOLDER%\artifacts\%PLATFORM%"
- cmd: 7z a %APPVEYOR_PROJECT_NAME%-%PLATFORM%.zip "%APPVEYOR_BUILD_FOLDER%\artifacts\%PLATFORM%"
test: off
artifacts:
  - path: $(APPVEYOR_PROJECT_NAME)-*.zip
    name: $(APPVEYOR_PROJECT_NAME)
deploy:
- provider: Environment
  name: BUILDBOT
  on:
    appveyor_repo_tag: true