version: 4.0.{build}
image: Visual Studio 2022
configuration:
- Release
platform:
- Any CPU
branches:
  only:
    - master
    - devel
  except:
    - gh-pages
install:
- cmd: git submodule -q update --init
- cmd: choco install advanced-installer 
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- nuget restore
skip_commits:
  files:
    - doc/*
    - .github/*
    - extras/*
    - '**/*.md'
build_script:
- ps: Installer/Build.ps1
after_build:
- ps: Installer/PostBuild.ps1
test: off
cache:
- '%USERPROFILE%\.nuget\packages'
artifacts:
  - path: "artifacts\\DS4Windows.Setup.exe"
    name: $(APPVEYOR_PROJECT_NAME)
  - path: "artifacts\\Publish.zip"
    name: "Source"
deploy:
- provider: Environment
  name: BUILDBOT
  on:
    appveyor_repo_tag: true